#include <iostream>
#include "fstream"
#include "Vector.h"
#include "String.h"
#include "User.h"
#include "Session.h"

void PrintCommandsForLibrary() {
	std::cout << "Here are the commands you can do:" << std::endl;
	std::cout << "You have to be logged in to make this operations:" << std::endl;
	std::cout << "You can add or remove users only if you are admin - users add | remove (name)" << std::endl;
	std::cout << "You can add or remove books only if you are admin" << std::endl;
	std::cout << "You can view all books, find one book and sort books by criteria \n" << std::endl;

	std::cout << "If you are not logged in or you dont have account - ask the administrator to create account for you.If you have \n account you can sign in by typing log in and writing the correct information" << std::endl;

}
int Engine(String& path) {
	std::ifstream in;
	in.open(path.data, std::ios::in);
	if (!in.is_open())
	{
		return 1;
	}
	Session session(path);

	//At the very beginning i check if the file exists. If it doesnt i made the function to return a int. So i return 1 if it doesnt exists
	std::cout << "If you want the program to end write : \"close\"" << std::endl;
	PrintCommandsForLibrary();


	String command;
	do
	{
		command = "";
		std::cout << "Enter command: ";
		std::cin >> command;
		if (command == "")
			continue;
		if (command == "login")
			session.LogInUser();
		else if (command == "logout")
			session.LogoutUser();
		else if (command == "users")
			session.AdminUsersControl(path);
		else if (command == "books")
			session.BookSplit();
		else if (command == "save")
			session.SaveBooks(path);
		else if (command == "exit")
			std::cout << "You have to close the file in order to exit the program" << std::endl;
		else if (command == "saveas")
		{
			String newPath;
			std::cin >> newPath;
			session.SaveBooks(newPath);
			std::cout << "Succesfully saved at: " << newPath << std::endl;
		}
		else if (command == "close")
			continue;
		else
			std::cout << "Invalid command! \n";
	} while (!(command == "close"));

	std::cout << "Succesfully closed the file" << std::endl;
}
int main() {
	String command;
	do
	{
		command = "";
		std::cin >> command;
		if (command == "open")
		{
			String path;
			std::cin >> path;

			//Making local check if the file exists
			int result = Engine(path);
			if (result == 1)
			{
				std::cout << "The file with name " << path << " doesn't exist" << std::endl;
				continue;
			}
		}
		else if (command == "help")
		{
			std::cout << "The following commands are supported" << std::endl;
			std::cout << "open <path>(supported only for books) - opens <file>" << std::endl;
			std::cout << "save - saves the information which has been generated by the current session in the openeed file";
			std::cout << "saveas <path> - saves the information which has been generated by the current session in other file";
			std::cout << "close	- closes the currently open file(for users)" << std::endl;
			std::cout << "exit	- closes the program" << std::endl;
			std::cout << "help	- prints the information about the commands" << std::endl;
		}
		else if (command == "save" || command == "saveas")
		{
			std::cout << "You have to open file and be logged in to do these operations"<<std::endl;
			continue;
		}
		else
		{
			std::cout << "Invalid command! Type \"help\" to see all the commands" << std::endl;
			continue;
		}
	} while (!(command == "exit"));
}